services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=student_service_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    ports:
      - "8500:8500"
    command: "agent -dev -client 0.0.0.0"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres-db
      - redis
      - consul-server
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - REDIS_HOST=redis
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8089:8089"

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres-db
      - consul-server
    environment:
      - DB_HOST=postgres-db
      - DB_USERNAME=${DB_USERNAME:-postgres} # Add this
      - DB_PASSWORD=${DB_PASSWORD:-password} # Add this
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
      - "8087:8087"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - consul-server
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_QUERY_PASSING=true
      - SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER=true
    ports:
      - "8081:8081"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
    - postgres-db
    - consul-server
    environment:
    - DB_HOST=postgres-db
    - DB_PORT=5432       # Add this line
    - DB_USERNAME=${DB_USERNAME:-postgres}
    - DB_PASSWORD=${DB_PASSWORD:-password}
    - SPRING_CLOUD_CONSUL_HOST=consul-server
    - SPRING_CLOUD_CONSUL_PORT=8500
    ports:
    - "8091:8091"
