server.port=8087
spring.application.name=user-service

# Use the Docker service name 'postgres-db'
spring.datasource.url=jdbc:postgresql://postgres-db:5432/student_service_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# --- Consul Discovery ---
# Use the Docker service name 'consul-server'
spring.cloud.consul.host=consul-server
spring.cloud.consul.port=8500

# UNIQUE ID for registration
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

# IMPORTANT: Remove hostname=127.0.0.1. Let Consul use the internal Docker IP.
spring.cloud.consul.discovery.prefer-ip-address=true

# --- Liquibase ---
spring.liquibase.enabled=false