package user_service.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import user_service.entity.UserEntity;
import user_service.service.UserService;
import java.util.List;


@RestController
@RequestMapping("/users")
public class UserController {

    private final UserService service;
    public UserController(UserService service) { this.service = service; }

    // USE CASE: Create New Profile (Admin usage)
    @PostMapping
    public ResponseEntity<UserEntity> createProfile(@RequestBody UserEntity user) {
        return new ResponseEntity<>(service.createUser(user), HttpStatus.CREATED);
    }

    // USE CASE: Signup (Self-registration)
    @PostMapping("/signup")
    public ResponseEntity<String> signup(@RequestBody UserEntity user) {
        service.createUser(user);
        return ResponseEntity.ok("User registered successfully. Please sign in.");
    }

    // USE CASE: Signin (Verification check)
    // Note: Actual JWT is generated by auth-service, this checks user existence
    @PostMapping("/signin-check")
    public ResponseEntity<String> signinCheck(@RequestParam String email) {
        service.verifyUserActive(email);
        return ResponseEntity.ok("User is valid");
    }

    // USE CASE: Get My Profile
    @GetMapping("/profile/{id}")
    public ResponseEntity<UserEntity> getProfile(@PathVariable Long id) {
        return ResponseEntity.ok(service.getUserById(id));
    }

    // USE CASE: Update Profile (User Edit)
    @PutMapping("/profile/{id}")
    public ResponseEntity<UserEntity> updateProfile(@PathVariable Long id, @RequestBody UserEntity user) {
        return ResponseEntity.ok(service.updateUser(id, user));
    }

    // USE CASE: Role-Based Access (Fetch only specific roles)
    @GetMapping("/role/{roleName}")
    public List<UserEntity> getUsersByRole(@PathVariable String roleName) {
        return service.searchByRole(roleName);
    }

    // USE CASE: Forgot Password (Initiate)
    @PostMapping("/forgot-password")
    public ResponseEntity<String> forgotPassword(@RequestParam String email) {
        service.initiatePasswordReset(email);
        return ResponseEntity.ok("Reset instructions sent to your email");
    }

    // USE CASE: Reset Password (Execute)
    @PostMapping("/reset-password")
    public ResponseEntity<String> resetPassword(@RequestParam String token, @RequestBody String newPassword) {
        service.resetPassword(token, newPassword);
        return ResponseEntity.ok("Password has been reset successfully");
    }

    // USE CASE: Delete Profile (Soft Delete/Hard Delete)
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteProfile(@PathVariable Long id) {
        service.deleteUser(id);
        return ResponseEntity.noContent().build();
    }
}